matrix:
  include:
  - os: linux
    language: d
    d: dmd
  - os: linux
    language: d
    d: ldc
  - os: osx
    language: d
    d: dmd
  - os: osx
    language: d
    d: ldc
  - os: windows
    language: shell
    env: DC=C:\\tools\\ldc2
before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install ldc;
      choco install make;
  fi
script:
- dir C:\\tools
- ren C:\\tools\\ldc2-*-windows-x64 C:\\tools\\ldc2
- dir C:\\tools
- make test DCOMPILER=$DC
- echo "Done"
