matrix:
  include:
  - os: linux
    language: d
    d: dmd
  - os: linux
    language: d
    d: ldc
  - os: osx
    language: d
    d: dmd
  - os: osx
    language: d
    d: ldc
  - os: windows
    language: shell
    env: DC=C:\\tools\\ldc2-1.23.0-windows-x64
before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install ldc;
      choco install make;
      dir C:\\tools;
  fi
script:
- make test DCOMPILER=$DC
- echo "Done"
