matrix:
  include:
  - os: linux
    language: d
    d: dmd
  - os: linux
    language: d
    d: ldc
  - os: osx
    language: d
    d: dmd
  - os: osx
    language: d
    d: ldc
  - os: windows
    language: shell
    env: DC=C:\tools\ldc2.exe
before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install ldc;
      choco install make;
  fi
script:
- make test DCOMPILER=$DC
- echo "Done"
