# Workflow based on Github Actions sample workflow and the
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run helloworld app
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Dub Build and Run
        shell: bash
        run: |
          dub build
          dub run
          dub clean
          make clean

      - name: Make Build and Run
        shell: bash
        run: |
          make test DCOMPILER=${DC}
          make clean

      - name: Make Build and Run 64-bit
        shell: bash
        run: |
          make test DCOMPILER=${DC} DFLAGS=-m64
