# Workflow exploring Github Actions on Windows
name: D Windows Environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run helloworld app
    strategy:
      matrix:
        os: [windows-latest]
        dc: [dmd-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Environment Check
        shell: bash
        run: |
          type -p dub
          type -p ${DC}
          type -p make
          type -p dos2unix
          type -p unix2dos
          dub --version
          ${DC} --version
          make --version
          dos2unix --version
          unix2dos --version
          ls -1 C:\msys64\*
